config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import HomeView, AboutView, ProductsView, ProductListWithType

app_name = 'mainapp'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('products/', ProductsView.as_view(), name='products'),
    path('products/<slug:slug>', ProductListWithType.as_view(), name='products_type'),
]

mainapp/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class BaseModel(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(BaseModel, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True

class Category(BaseModel):
    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoriyalar'


class Type(BaseModel):
    image = models.ImageField(upload_to='category/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    description = models.TextField(null=True, blank=True)

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return "Image is not defined"


class Product(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)
    size = models.IntegerField(null=True)
    manfacturer = models.CharField(max_length=100, null=True)
    theory = models.IntegerField(null=True)
    unit = models.CharField(max_length=20, null=True)
    price_cash = models.IntegerField(null=True)
    price_cashless = models.IntegerField(null=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import DetailView, ListView, UpdateView, DeleteView, CreateView, TemplateView
from .models import Type, Product

class HomeView(TemplateView):
    template_name = 'mainapp/home.html'


class AboutView(TemplateView):
    template_name = 'mainapp/about.html'



class ProductsView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'mainapp/products.html'


class ProductListWithType(View):
    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        products = Product.objects.filter(type__slug=slug)
        context = {
            'products': products,
        }
        return render(request, 'mainapp/products.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
<!--      <link rel="stylesheet" href="{% static 'css/style1.css' %}">-->
    <!--- owl carusel -->
      <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <link rel="stylesheet" href="https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
{% block head %}
{% endblock %}
</head>
<body class="main-layout">
<div class="loader_bg">
      <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#"/></div>
      </div>
      <div id="mySidepanel" class="sidepanel">
         <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
         <a class="active" href="/">Home</a>
         <a href="#">About</a>
         <a href="{% url 'mainapp:products' %}">Products</a>
         <a href="#">Contact</a>
      </div>
      <!-- end loader -->
{% include 'navbar.html ' %}

{% block body %} {% endblock %}
      <!--  footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row">
                  <div class="col-md-8 offset-md-2">
                     <div class="news">
                        <h3>Newsletter</h3>
                        <form class="form_news">
                           <input class="newsltter" placeholder="enter your email" type="type" name="enter your email">
                           <button class="sunm_btn">SUBSCRIBE</button>
                        </form>
                     </div>
                  </div>
                  <div class=" col-md-10 offset-md-1">
                     <ul class="conta">
                        <li><i class="fa fa-map-marker" aria-hidden="true"></i>Locations
                        </li>
                        <li><i class="fa fa-volume-control-phone" aria-hidden="true"></i> +71 1234567890</li>
                        <li> <i class="fa fa-envelope" aria-hidden="true"></i><a href="#"> demo@gmail.com</a></li>
                     </ul>
                  </div>
                  <div class="col-md-12">
                     <ul class="social_icon">
                        <li><a href="Javascript:void(0)"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="Javascript:void(0)"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="Javascript:void(0)"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                        <li><a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-10 offset-md-1">
                        <p>Copyright 2020  All Right Reserved By <a href="https://html.design/"> Free Html Templates</a></p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
<!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script>
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:4
            }
        }
    })
    </script>
</body>
</html>

templates/mainapp/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock %}

{% block body %}
<div class="container">
    <h1>About page</h1>
</div>
{% endblock %}

templates/mainapp/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block body %}
<!--- header -->
<section>
<header class="full_bg">
         <section class="banner_main">
            <div id="myCarousel" class="carousel slide banner" data-ride="carousel">
               <ol class="carousel-indicators">
                  <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                  <li data-target="#myCarousel" data-slide-to="1"></li>
                  <li data-target="#myCarousel" data-slide-to="2"></li>
               </ol>
               <div class="carousel-inner">
                  <div class="carousel-item active">
                     <div class="container">
                        <div class="carousel-caption  banner_po">
                           <div class="row">
                              <div class="col-md-8">
                                 <div class="build_box text_align_left">
                                    <h1>WELCOME<br> <span class="white">METALS FACTORY</span></h1>
                                    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,</p>
                                    <a class="read_more conatct_btn" href="#contact" role="button">Contact now</a>
                                    <a class="read_more conatct_btn" href="#about" role="button">About Factory</a>
                                 </div>
                              </div>
                           </div>
                           <strong>best</strong>
                        </div>
                     </div>
                  </div>
                  <div class="carousel-item">
                     <div class="container">
                        <div class="carousel-caption banner_po">
                           <div class="row">
                              <div class="col-md-8">
                                 <div class="build_box text_align_left">
                                    <h1>WELCOME<br> <span class="white">METALS FACTORY</span></h1>
                                    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,</p>
                                    <a class="read_more conatct_btn" href="#contact" role="button">Contact now</a>
                                    <a class="read_more conatct_btn" href="#about" role="button">About Factory</a>
                                 </div>
                              </div>
                           </div>
                           <strong>best</strong>
                        </div>
                     </div>
                  </div>
                  <div class="carousel-item">
                     <div class="container">
                        <div class="carousel-caption banner_po">
                           <div class="row">
                              <div class="col-md-8">
                                 <div class="build_box text_align_left">
                                    <h1>WELCOME<br> <span class="white">METALS FACTORY</span></h1>
                                    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,</p>
                                    <a class="read_more conatct_btn" href="#contact" role="button">Contact now</a>
                                    <a class="read_more conatct_btn" href="#about" role="button">About Factory</a>
                                 </div>
                              </div>
                           </div>
                           <strong>best</strong>
                        </div>
                     </div>
                  </div>
               </div>
               <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
               <i class="fa fa-angle-left" aria-hidden="true"></i>
               <span class="sr-only">Previous</span>
               </a>
               <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
               <i class="fa fa-angle-right" aria-hidden="true"></i>
               <span class="sr-only">Next</span>
               </a>
            </div>
         </section>
      </header>
      <!-- end banner -->
   <!-- about -->
      <div id="about" class="about">
         <div class="bg_about">
            <div class="container">
               <div class="row d_flex">
                  <div class="col-md-5">
                     <div class="about_img">
                        <figure><img src="{% static 'images/about.jpg' %}" alt="#"/></figure>
                     </div>
                  </div>
                  <div class="col-md-6 offset-md-1">
                     <div class="titlepage text_align_right">
                        <h2>About of Factory</h2>
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis Theme natoque penatibus et magnis dis parturient montes, nascetur.
                           natoque penatibus et magnis dis parturient montes, nascetur.
                        </p>
                        <a class="read_more" href="{% url 'mainapp:about' %}">About Us</a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end about -->
      <!-- products -->
<section>
      <div id="product" class="prot">
         <div class="products">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <div class="titlepage text_align_left">
                        <h2>Metal Products</h2>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,</p>
                     </div>
                  </div>
               </div>
            </div>
            <div class="container">
            <div class="row owl-carousel owl-theme ">
         {% for type in types %}
            <div class="product_data item container">
                  <div class="card">
                     <div class="card-body product mar_bottom30">
                        <a href="{% url 'mainapp:products_type' type.slug %}">
                           <div class="category-image">
                              <img src="{{ type.image_url }}" alt="Product image" style="height: 16rem;">
                           </div>
                           <h3 class="text-center">{{ type.name }}</h3>
                        </a>
                     </div>
                  </div>
            </div>
         {% endfor %}
         </div>
            </div>
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <a class="read_more" href="{% url 'mainapp:products' %}">See More</a>
                  </div>
               </div>
            </div>
            </div>

         </div>
      </div>
   </section>
      <!-- end products -->
   <!--  contact -->
      <div id="contact" class="contact">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="bg_yeloow">
                     <div class="titlepage text_align_center">
                        <h2>Contact Us</h2>
                     </div>
                     <div class="row">
                        <div class="col-md-10 offset-md-1">
                           <form id="request" class="main_form">
                              <div class="row">
                                 <div class="col-md-12 ">
                                    <input class="contactus" placeholder="Name" type="type" name=" Name">
                                 </div>
                                 <div class="col-md-12">
                                    <input class="contactus" placeholder="Email" type="type" name="Email">
                                 </div>
                                 <div class="col-md-12">
                                    <input class="contactus" placeholder="Phone Number" type="type" name="Phone Number">
                                 </div>
                                 <div class="col-md-12">
                                    <textarea class="textarea" placeholder="Message" type="type" Message="Name">Message</textarea>
                                 </div>
                                 <div class="col-md-12">
                                    <button class="send_btn">Send</button>
                                 </div>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end contact -->

{% endblock %}
</section>

templates/mainapp/products.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Products{% endblock %}
{% block head %}
<style>
.dropbtn {
  background-color: rgb(20, 20, 165);
  color: white;
  padding-left: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
  display: block;
}

.dropdown:hover .dropbtn {
  background-color: rgb(20, 20, 165);
}

    #header1 {
      content: "";
      background-color: rgb(20, 20, 139);
      padding: 10px;
      margin-top: 10px;
      display: flex;
      text-align: center;
    }


   p{
    height:  50px;
    font-size: 20px;
    margin-left: 165px;
   }

   #main-content {
      padding: 100px;
      margin-left: 100px;
   }


.intro {
  height: 100%;
  margin-top: 50px;
}

table td,
table th {
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}

thead th {
  color: #fff;
}

.card {
  border-radius: .5rem;
}

.table-scroll {
  border-radius: .5rem;
}

.table-scroll table thead th {
  font-size: 1.25rem;
}
thead {
  top: 0;
  position: sticky;
}

</style>
{% endblock %}
{% block body %}
<section>
<div id="header1">
  <div>
    {% for category in categories %}
    <div class="dropdown">
        <h2 class="dropbtn">{{ category.name }}</h2>
        <div class="dropdown-content">
          {% for type in types %}
            {% if 1 == 1 %}
        <a href="#">{{ type.name }}</a>
          {% else %}
                  <a href="#">link1</a>
            {% endif %}
          {% endfor %}
        </div>
    </div>
    {% endfor %}
  </div>
</div>
<div class="container intro">
  <div class="bg-image h-100" style="background-color: #f5f7fa;">
    <div class="mask d-flex align-items-center h-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12">
            <div class="card">
              <div class="card-body p-0">
                <div class="table-responsive table-scroll" data-mdb-perfect-scrollbar="true" style="position: relative; height: auto">
                  <table class="table table-striped mb-0">
                    <thead style="background-color: #002d72;">
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Size</th>
                        <th scope="col">Theory</th>
                        <th scope="col">Manfacturer</th>
                        <th scope="col">Unit</th>
                        <th scope="col">Price</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for product in products %}
                      <tr>
                        <td>{{ product.name }}</td>
                        <td>{{ product.size }}</td>
                        <td>{{ product.theory }}</td>
                        <td>{{ product.manfacturer }}</td>
                        <td>{{ product.unit }}</td>
                        <td>${{ product.price_cash }}</td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
{% endblock %}

templates/navbar.html
     {% load static %}
      <!-- header -->
         <!-- header inner -->
<nav>
         <div class="header">
            <div class="container-fluid">
               <div class="row d_flex">
                  <div class=" col-md-2 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="/"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>

                  <div class="col-md-10 col-sm-9">
                     <ul class="site_menu text_align_right">
                        <li >
                           <button class="openbtn" onclick="openNav()"><img src="{% static 'images/menu_icon.png' %}"></button>
                        </li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
</nav>
         <!-- end header inner -->